trigger:
- optimize_v2

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        
      displayName: 'npm install, build and test'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/green-insight-backend.zip
        replaceExistingArchive: true
    - upload: $(Build.ArtifactStagingDirectory)/green-insight-backend.zip
      artifact: drop
    

- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: VMDeploy
    displayName: Web deploy
    environment:
      name: deployvmlatest
      resourceType: VirtualMachine
    strategy:
      rolling:
        maxParallel: 2  #for percentages, mention as x%

        deploy:
          steps:
          - download: current
            artifact: drop
          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
                cd /home/azureuser/green-insight-backend
                sudo rm -rf *
                sudo rm -rf .git/
                sudo rm -rf .gitignore
                sudo unzip /home/azureuser/azagent/_work/2/drop/green-insight-backend.zip -d /home/azureuser/green-insight-backend
                cd /home/azureuser/green-insight-backend/App
                sudo rm -rf node_modules
                sudo npm install
                pm2 restart 0
